### ISSUE TITLE
What license are the screenshots in the README released under?

### ISSUE THREAD

**Issue by fusion809** [lcpz/awesome-copycats#196]
Hi,

I'd like to use the screenshots in the README.md in a blog post I'm writing comparing the various DEs / WMs. So I want to know what license they're released under? BY-NC-SA to? 

Thanks for your time

**Comment by copycat-killer** [comment]
Hi, thank you for your interest.

They showcase the themes, so yes, technically the license is the same.

Give me a link of your post when it's done. 😃

**Comment by fusion809** [comment]
Thanks and shall do.
