### ISSUE TITLE
vertex: vertical size of dock indicators

### ISSUE THREAD

**Issue by ngoonee** [lcpz/awesome-copycats#200]
I'm unsure if this is related to screen resolution (makes sense that it would be), but for reference all my screens are at 1920x1080, and this also happens at a lower resolution of 1366x768.

When the dock is hidden/minimized, the blue bar indicator (showing an occupied tag) takes a larger proportion of the dock than when it is shown/revealed. Here's a screenshot, showing the left-most part of my screen both when the dock is hidden/minimized (left) and when it is shown/revealed (right). The dock's size does not change, but that blue bar indicator is differently sized.

![2017-09-27-163228_3840x1080_scrot](https://user-images.githubusercontent.com/135656/30903555-c6b61b66-a3a1-11e7-874c-4963f83a7cd7.png)

It would be more useful for both to have the same sizes, as then it would be possible to tell which tag has clients just from a glance without having to either mouseover of switch tags to reveal the dock.

The corollary problem caused by this is that the 8th/9th tag's status (occupied or not) don't show on the dock when it is hidden/minimized.

**Comment by lcpz** [comment]
That's because `icons/taglist_square_{sel,unsel}` is a PNG. The problem could be solved by using Cairo instead. I don't know if it's possible, though. I'll investigate when I have the time.
