### ISSUE TITLE
Quake configuration not working by default with termite

### ISSUE THREAD

**Issue by nikkolasg** [lcpz/awesome-copycats#203]
Hi there,

I wanted to changed terminal emulator to give a try with Termite. Unfortunately, I spend quite some time figuring out why termite does not work with the drop down quake utility (attempt to index a nil value, such as [here](https://github.com/lcpz/lain/issues/361) ).
In fact, termite do **not** have a `-name` option but a `--name` option. 

I'm not a deep awesomewm / lain  expert so for the moment i modified my local version of vain, when it spawns the shell the first time (around line 57 in quake.lua). 
Do you think it would be possible to add a wrapper to your themes so it detects the correct option ? 
or at least explicitly say somewhere to check the exact semantics of the terminal options one is using to make it work with quake, and specificy the line of code to change or stg ?
Is there a better way to fix this than my hackish method ?

Thank you !

**Comment by lcpz** [comment]
Hi, if you had read the [issue template](https://github.com/lcpz/awesome-copycats/blob/master/ISSUE_TEMPLATE.md#if-you-have-an-issue), you'd have found the solution both in [previous issues](https://github.com/lcpz/lain/issues?utf8=%E2%9C%93&q=termite) and lain's [wiki](https://github.com/lcpz/lain/wiki/Utilities#quake).
