### ISSUE TITLE
attempt to index field 'layout' (a nil value)

### ISSUE THREAD

**Issue by norozap** [lcpz/awesome-copycats#207]
Hi,

I followed installation instructions and every theme I switch to gives me the same error. I have searched through the lain issues as well and couldn't find anything related to my issue.

2017-10-12 22:28:15 /usr/share/awesome/lib/beautiful/xresources.lua:54: W: Failed to get xrdb value 'background'.
2017-10-12 22:28:15 W: beautiful: can't get colorscheme from xrdb (using fallback).
error while running function!
stack traceback:
        /home/$USER/.config/awesome/rc.lua:149: in main chunk
error: /home/$USER/.config/awesome/rc.lua:149: attempt to index field 'layout' (a nil value)

Is this an issue with the beautiful library?

rc.lua:149 as follows:

lain.layout.termfair.nmaster           = 3

$ awesome -v
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

$ lua -v
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

Distributor ID: Debian
Description:    Debian GNU/Linux 9.1 (stretch)
Release:        9.1
Codename:       stretch

Any help with this? I have not changed anything in rc.lua file, just the theme to test.

Thanks!

**Comment by lcpz** [comment]
Seems that `lain` is not installed properly. Try cloning it yourself.

**Comment by norozap** [comment]
Hi,

I had tried that already. Before I saw your answer, I cloned all repos again from scratch and was able to get it working. It seems something failed to download in transport, or I had an older version of the master branch.

Thanks!
