### ISSUE TITLE
multi-monitors: Disabling a screen using xrandr when there are clients attached to it causes these clients to be unraisable

### ISSUE THREAD

**Issue by liquiddandruff** [lcpz/awesome-copycats#209]
Theme: powerarrow-dark
Config version: 3 weeks ago (a7d9f90)

```
$ awesome -v
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```

Hello,

I've been encountering this issue for a while now after using my laptop more both as a workstation and on-the-go. As the title says, when I run ```xrandr --output HDMI1 --off```, clients that have been started from HDMI1 or moved to HDMI1 will become unraisable. 

Clients that were on the screen at the moment of being disabled are never moved back to the primary screen (i.e, does not even appear on the primary screen's menubar, minimized or otherwise). 

Clients that have been moved back manually to the primary screen prior to disabling the display it came from (e.g, HDMI1) _are_ however shown in a minimized state on the primary screen, but trying to raise them (restore unminized) has no effect--they remain minimized, and therefore unusable.

No errors are displayed when this happens.

The only fix I've found is to forcibly restart awesome. This then fixes every client and makes them usable again.

Thanks

**Comment by liquiddandruff** [comment]
I suspect it does, but I'll try it once I finish what I'm working on at the moment. Will report back.

**Comment by lcpz** [comment]
@liquiddandruff You must be working on something big. 😃

**Comment by liquiddandruff** [comment]
Apologies for the delay :joy: 

I think you're right to suspect this behaviour is due to awesome itself. After removing `~/.config/rc.lua` and restarting awesome so it would use the default rc.lua, I started a few clients on both screens and then disconnected HDMI1 as per usual. The exact same scenario occurs; clients started on the HDMI1 screen are moved to the primary display but are unraisable. Restarting awesome fixes it.

I'd have thought something like this should be caught sooner, but a cursory search on reported issues in the awesome repo seems to indicate otherwise. I find that hard to believe, but I'll submit an issue there anyways.

Will update here if anything changes.

**Comment by liquiddandruff** [comment]
Just an update that this has been confirmed as a bug https://github.com/awesomeWM/awesome/issues/2088 and a fix should come soon.
