### ISSUE TITLE
How to read powerarrow binclock?

### ISSUE THREAD

**Issue by ckozler** [lcpz/awesome-copycats#214]
I'm sorry since this is probably glaringly obvious and I am just missing something simple..

How do you read the clock in powerarrow? I thought it was just a gimmick animation in the corner and was getting annoyed there was no clock in powerarrow so started to set one up...only to see in the theme its actually an LUA script called binclock

So how do I read it in the corner?

**Comment by lcpz** [comment]
https://en.wikipedia.org/wiki/Binary_clock#Binary-coded_sexagesimal_clocks
