### ISSUE TITLE
[featurerequest] changing Network-Icon with changing

### ISSUE THREAD

**Issue by TheRojam** [lcpz/awesome-copycats#223]
I saw a beautiful widget that would be nice to get implemented.
I was trying myself, but didn't worked.
If you would implement https://github.com/pltanton/net_widgets in powerarrow dark it would be beautiful.
So i mean that there is only the "wifi" symbol. but no indecator for wired or wireless or even 3g connection.

thank you

**Comment by lcpz** [comment]
I did it for [Vertex](https://camo.githubusercontent.com/529ce51efbafee9cdbc95724693ee85b120ea9dc/687474703a2f2f646f7473686172652e69742f7075626c69632f696d616765732f75706c6f6164732f313433322e6a7067).

[This](https://github.com/lcpz/awesome-copycats/blob/master/themes/vertex/theme.lua#L231-L271) is the snippet. It's trivial to adapt to your wishes. In particular, `perc` is the percentage of signal strength.
