### ISSUE TITLE
attempt to call a nil value (field 'at_screen_connect')

### ISSUE THREAD

**Issue by kieranajp** [lcpz/awesome-copycats#225]
Hey,

I seem to be running into a problem with your themes, and I wonder if you can help me debug it.

The default version of awesome works fine, and I tried downloading a different theme entirely and that worked too. However, I like yours better ;)

I've downloaded a fresh version of your themes, to make sure it's not one of my modifications causing this, but it doesn't look like it.

The error I'm getting is:

```
Oops, an error happened!
~/.config/awesome/rc.lua:214: attempt to attempt to call a nil value (field 'at_screen_connect')
```

I guess that something is going wrong initialising the theme, as that function is defined in the theme file. But I'm not really familiar enough with Lua to be able to effectively debug it.

Here's also the content of my ~/.xsession-errors:

```
2018-02-25 16:50:54 E: Error during a protected call: /home/kieran/.config/awesome/lain/widget/fs.lua:77: attempt to index a nil value (local 'info')
stack traceback:
        /home/kieran/.config/awesome/lain/widget/fs.lua:77: in local 'func'
        /usr/share/awesome/lib/gears/object.lua:143: in function 'gears.object.emit_signal'
        /home/kieran/.config/awesome/lain/helpers.lua:96: in function 'lain.helpers.newtimer'
        /home/kieran/.config/awesome/lain/widget/fs.lua:125: in function 'lain.widget.fs'
        /home/kieran/.config/awesome/themes/multicolor/theme.lua:126: in main chunk
        [C]: in function 'dofile'
        [C]: in function 'xpcall'
        /usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
        (...tail calls...)
        /usr/share/awesome/lib/beautiful/init.lua:196: in function 'beautiful.init'
        /home/kieran/.config/awesome/rc.lua:175: in main chunk
2018-02-25 16:50:54 E: beautiful: error loading theme file /home/kieran/.config/awesome/themes/multicolor/theme.lua
error while running function!
stack traceback:
        /home/kieran/.config/awesome/rc.lua:215: in local 'func'
        /usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
        /home/kieran/.config/awesome/rc.lua:214: in main chunk
error: /home/kieran/.config/awesome/rc.lua:215: attempt to call a nil value (field 'at_screen_connect')
2018-02-25 16:50:54 W: awesome: a_glib_poll:432: Last main loop iteration took 0.139775 seconds! Increasing limit for this warning to that value.
```

As well as my awesome and lua versions:

```
 ~ awesome -v
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
 ~ lua -v
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
```

* expected behavior and actual behavior
* steps to reproduce the problem
* X error log (if needed)

**Comment by kieranajp** [comment]
Actually, I managed to fix it by removing all references to the `fs` widget from my theme; though it would be good to understand why this is causing it to crash.

Will close the issue for now.

**Comment by lcpz** [comment]
> it would be good to understand why this is causing it to crash

[This variable](https://github.com/lcpz/lain/blob/master/widget/fs.lua#L76) becomes `nil`.

Some partition on your system doesn't provide informations. At least, `Gio` isn't able to fetch them.

This is strange, I didn't think it could happen. I'll add a check.

**Comment by lcpz** [comment]
Done. Please try latest commit.

**Comment by kieranajp** [comment]
Yep - that did it. Thank you for your help, for explaining to me, and for the great themes :)
