### ISSUE TITLE
how to enable tag based wallpapers

### ISSUE THREAD

**Issue by Pascal3366** [lcpz/awesome-copycats#229]
Hi, i have a question:
I want to implement a feature that each Workspace/Tag has another wallpaper.
I found a solution here:
https://askubuntu.com/questions/78629/can-i-set-different-backgrounds-for-different-workspaces-tags-in-awesome-wm

But i am unable to achieve this with your config.
Im using the theme powerarrow-dark.

Thanks in common.

**Comment by lcpz** [comment]
This is independent from the theme. All you have to do is modify [this function](https://github.com/lcpz/awesome-copycats/blob/master/rc.lua.template#L201-L212).

Adapting that ancient code, you could try:

```lua

local mywalls = {
    [1] = { -- screen 1
        [1] = "/path/to/tag1-1/wall", -- tag 1
        [2] = "/path/to/tag1-2/wall", -- tag 2
        -- and so on
    },
    [2] = { -- screen 2
        [1] = "/path/to/tag2-1/wall", -- tag 1
        [2] = "/path/to/tag2-2/wall", -- tag 2
        -- and so on
    },
    -- and so on
}

screen.connect_signal("property::geometry", function(s)
    awful.tag.attached_connect_signal(s "request::select", function(tag)
          gears.wallpaper.maximized(mywalls[s.index][tag.index], s, true)       
    end)
end)
```

**Comment by Pascal3366** [comment]
Thanks, I tried to implement that but now all wallpapers of all tags are just black.

**Comment by lcpz** [comment]
There is a typo [here](https://github.com/Pascal3366/dotfiles-2018/blob/master/awesome/.config/awesome/rc.lua#L239): put a comma after the `s`.

**Comment by Pascal3366** [comment]
Ok i fixed that typo, but still the wallpaper stays black
I have no idea where the error could be...

**Comment by Pascal3366** [comment]
Oh i just ran my config using a lua interpreter and it said 'gears not found'
How can i install gears?
I am using archlinux

**Comment by lcpz** [comment]
Let us do it in another way.

Put the following at the bottom of your `rc.lua`:

```lua
local mywallpaper = {
    [1] = "path/to/tag1/wall",
    [2] = "path/to/tag2/wall",
    -- and so on
}

local function set_wallpaper_tag(t)
    if t.selected then
        gears.wallpaper.maximized(mywallpaper[t.index], t.screen, true)
    end
end

tag.connect_signal("property::selected", function(t)
    gears.timer.delayed_call(set_wallpaper_tag, t)
end)
```

**Comment by Pascal3366** [comment]
WOW it worked!
You're a genius. 
Thank you very very much :D
