### ISSUE TITLE
Slackware 14.2 and fs widget

### ISSUE THREAD

**Issue by Incognito4nonymous** [lcpz/awesome-copycats#232]
Hi again !

So I did my yearly update of the copycat repository, by pulling a git from here, to start configuration from scratch and have a more recent code, and upon restarting awesome, I get back to the default Awesome theme, with a, error saying 

`rc.lua:214: attempt to call a nil value (field 'at_screen_connect')`
It seems to call something into /usr/share/awesome/lib/awful/screen.lua at line 438 that doesn't exist. 

Upon inspection, the only theme that seems untouched by the issue is Vertex...
In the meantime I go back to my previous configuration...

**Comment by lcpz** [comment]
Please do as requested [here](https://github.com/lcpz/awesome-copycats/blob/master/ISSUE_TEMPLATE.md#if-awesome-fails-to-start).

**Comment by Incognito4nonymous** [comment]
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.2

Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio

Sorry for the long answer time, btw, I'm now running on an old commit I slightly changed to fit my needs. Maybe a year old, so the fs widget doesn't to cause any trouble on it...

**Comment by lcpz** [comment]
I need also [this](https://github.com/lcpz/awesome-copycats/blob/master/ISSUE_TEMPLATE.md#if-awesome-fails-to-start).

**Comment by Incognito4nonymous** [comment]
Oh it doesn't fail to start, it falls back to the default theme as a failsafe mechanism.

**Comment by lcpz** [comment]
I need to know why. Also, which distro you have?

If it's the `fs` widget, just disable until you have `Gio >= 2.54`.

**Comment by Incognito4nonymous** [comment]
2018-05-09 22:43:35 E: Error during a protected call: /home/incognito/.config/awesome/lain/widget/fs.lua:74: attempt to call a nil value (field 'unix_mounts_get')
stack traceback:
	/home/incognito/.config/awesome/lain/widget/fs.lua:74: in local 'func'
	/usr/share/awesome/lib/gears/object.lua:143: in function 'gears.object.emit_signal'
	/home/incognito/.config/awesome/lain/helpers.lua:96: in function 'lain.helpers.newtimer'
	/home/incognito/.config/awesome/lain/widget/fs.lua:137: in function 'lain.widget.fs'
	/home/incognito/.config/awesome/themes/multicolor/theme.lua:126: in main chunk
	[C]: in function 'dofile'
	[C]: in function 'xpcall'
	/usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
	/usr/share/awesome/lib/beautiful/init.lua:196: in function 'beautiful.init'
	/home/incognito/.config/awesome/rc.lua:175: in main chunk
2018-05-09 22:43:35 E: beautiful: error loading theme file /home/incognito/.config/awesome/themes/multicolor/theme.lua
error while running function!
stack traceback:
	/home/incognito/.config/awesome/rc.lua:214: in local 'func'
	/usr/share/awesome/lib/awful/screen.lua:438: in function 'awful.screen.connect_for_each_screen'
	/home/incognito/.config/awesome/rc.lua:214: in main chunk
error: /home/incognito/.config/awesome/rc.lua:214: attempt to call a nil value (field 'at_screen_connect')
2018-05-09 22:43:36 W: awesome: a_glib_poll:432: Last main loop iteration took 0,133450 seconds! Increasing limit for this warning to that value.
2018-05-09 22:43:36 W: awesome: a_glib_poll:432: Last main loop iteration took 0,479288 seconds! Increasing limit for this warning to that value.

Fs indeed as you say, in the meantime I'm more at ease with my 2017 modified version, besides the mpd widget, everything from it works flawlessly and in a beautiful manner.

Btw sorry for asking, but are you the same guy that was taking care of the repo as before but with a new name ?

**Comment by lcpz** [comment]
Either update Gio to the requested version, or wait for yout distro maintainers to update it.

Refer to [this thread](https://github.com/lcpz/lain/issues/387) for updates.
