### ISSUE TITLE
autostart run_once

### ISSUE THREAD

**Issue by Konfekt** [lcpz/awesome-copycats#234]
Instead of
```lua
-- {{{ Autostart windowless processes
local function run_once(cmd_arr)
    for _, cmd in ipairs(cmd_arr) do
        findme = cmd
        firstspace = cmd:find(" ")
        if firstspace then
            findme = cmd:sub(0, firstspace-1)
        end
        awful.spawn.with_shell(string.format("pgrep -u $USER -x %s > /dev/null || (%s)", findme, cmd))
    end
end

run_once({ "unclutter -root" }) -- entries must be comma-separated
-- }}}
```
a cleaner solution to avoid starting programs twice after a restart of Awesome seems
```lua
awful.spawn.easy_async_with_shell("xrdb -query", 
    function(stdout, stderr, reason, exit_code)
        xresources = stdout
        xresources_name = "awesome.started"
        if not xresources:match(xresources_name) then
            awful.spawn.with_shell("xrdb -merge <<< " .. "'" .. xresources_name .. ":true'")
            -- Execute once for X server
            awful.spawn.with_shell("dex --environment Awesome --autostart --search-paths $XDG_CONFIG_HOME/autostart:$XDG_CONFIG_HOME/autostart/awesome")
        end
    end)
```
where the line `awful.spawn.with_shell("dex --environment Awesome --autostart --search-paths $XDG_CONFIG_HOME/autostart:$XDG_CONFIG_HOME/autostart/awesome")` is to your liking, for example, it could be `awful.spawn( "unclutter -root" )`.

The approach via `pgrep` is wonky, for example, it does not permit autostarting the same program multiple times, but with different parameters.

**Comment by lcpz** [comment]
> it does not permit autostarting the same program multiple times, but with different parameters

When should this be desiderable?

Also, you spawn an asynchronous shell, from which you spawn 2 synchronous shells. 3 shells for 1 job is lavish.

But if you can rewrite your solution in order to use 1 shell and be able to spawn multiple processes, I will merge it.

**Comment by Konfekt** [comment]
I do not understand. Which multiple processes? Why only one job?

**Comment by Konfekt** [comment]
Regarding desirability, this depends on the user which might autostart programs other than unclutter. For example, if one would like to autostart the files in the autostart folder, it might be necessary to call `dex` with different desktop environments.

**Comment by Konfekt** [comment]
If you prefer a single shell, you could rewrite the lua code into POSIX shell and call it in the single shell.

**Comment by lcpz** [comment]
The objective of `run_once` function is to get in input a vector of commands (string), and to spawn each of them if not in execution.

If you can write the function in order to allow this and without having to spawn shells within shells so to be efficient, then I can merge it.

**Comment by Konfekt** [comment]
Does
```lua
awful.spawn.with_shell(
    'if [[ "$(xrdb -query)" = *"awesome.started"* ]]; then; exit; fi;' ..
    'xrdb -merge <<< "awesome.started:true";' ..
    'dex --environment Awesome --autostart --search-paths "$XDG_CONFIG_HOME"/autostart;' ..
    'unclutter -root'
```
do it?

**Comment by lcpz** [comment]
Not completely: if for some reason my one of my autostart windowless processes is terminated and I restart Awesome, with the current code it gets respawned, while with yours it does not. Can you solve this?

**Comment by Konfekt** [comment]
Well, in this case the current code is the way to go. For example
```lua
 dex --environment Awesome --autostart --search-paths "$XDG_CONFIG_HOME"/autostart
  ```
terminates directly. 

Thus the user should decide on how he autostarts his commands: Those commands that run continuously and he wants to ensure to be loaded again by `run_once`, those that terminate or do not have to be loaded again by the above shell script.

By the way, by using the argument of pgrep
```
-a, --list-full           list PID and full command line
```
the findme construction
```lua
        findme = cmd
        firstspace = cmd:find(" ")
        if firstspace then
            findme = cmd:sub(0, firstspace-1)
        end
```
can be seemingly replaced by
```lua
        awful.spawn.with_shell("pgrep -u $USER -x -a '%s' > /dev/null || (%s)", cmd))
```

**Comment by Konfekt** [comment]
By the way, by using the argument of pgrep
```
-a, --list-full           list PID and full command line
```
the findme construction
```lua
        findme = cmd
        firstspace = cmd:find(" ")
        if firstspace then
            findme = cmd:sub(0, firstspace-1)
        end
```
can be seemingly replaced by
```lua
        awful.spawn.with_shell("pgrep -u $USER -x -a '%s' > /dev/null || (%s)", cmd))
```

**Comment by Konfekt** [comment]
The  idea was to make Awesome replicate the xdg autostart specification by
```lua
awful.spawn.with_shell(
    'if (xrdb -query | grep --quiet "^awesome\\.started:\\s*true$"); then; exit; fi;' ..
    'xrdb -merge <<< "awesome.started:true";' ..
    -- list each of your autostart commands, followed by ; inside single quotes, followed by ..
    'dex --environment Awesome --autostart --search-paths "$XDG_CONFIG_DIRS/autostart:$XDG_CONFIG_HOME/autostart"')
```
Then if a process is killed, I am not sure restarting the window manager is the way to go. This seems overkill.

Instead, programs I care about and die from time to time are kept alive by a cronjob check.

**Comment by lcpz** [comment]
> Instead, programs I care about and die from time to time are kept alive by a cronjob check.

It doesn't convince me to force use a daemon for something I use only during a X session.

> This has the advantage of run_once admitting spawing the same command with different arguments.

So using an additional flag, we can avoid your hardcoded shell script?

**Comment by lcpz** [comment]
Since we can't get both behaviours in one function, I simply added your code.

For implementing XDG autostart, you just have to remove lines [58](https://github.com/lcpz/awesome-copycats/commit/7168c4f08b3c2764fe9bb15a3773d1fcc0eded6f#diff-5f441214cbe572cd83b015f54ec9ee2cR58) and [65](https://github.com/lcpz/awesome-copycats/commit/7168c4f08b3c2764fe9bb15a3773d1fcc0eded6f#diff-5f441214cbe572cd83b015f54ec9ee2cR65).

**Comment by Konfekt** [comment]
As another side note, when using pgrep, the command should be searched literally if it contains special characters, like `grep -w` achieves. But this switch seems to be missing for `pgrep`.

**Comment by Konfekt** [comment]
Also, the switch `-f` is more to the point than `-a`, which also lists the PID (not of interest here).

**Comment by lcpz** [comment]
> As another side note, when using pgrep, the command should be searched literally if it contains special characters, like `grep -w` achieves. But this switch seems to be missing for `pgrep`.

I think `pgrep -x` does the job.

**Comment by Konfekt** [comment]
Not here:
```sh
--- ~ » pgrep -x -f 'urxvtd -q -o -f'                                                                                                    2 ↵
3131
--- ~ » pgrep -x 'urxvtd -q -o -f'   
```
