### ISSUE TITLE
attempt to index field 'filesystem' (a nil value)

### ISSUE THREAD

**Issue by szarvy** [lcpz/awesome-copycats#239]
hi!

Sorry for post that, but I have no ideas to solve the problem.
I only changed yet the rc.lua.template only, and this issue happened, when I'm starting or restarting awesome:
stack traceback: /.config/awesome/rc.lua:176: in main chunk
error: /.config/awesome/rc.lua:176 attempt to index field 'filesystem' (a nil value)

I tried to reclone lain, freedesktop, or the whole thing from fresh start. The same happend every time.
After that I tried to change the lgi version from 0.9.1 (stretch stable) to 0.9.2 (buster). (I'm on Debian 9.5)

Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.2

I really approciate your work, and I want to use this, but I can't figure it out what's wrong here...

(and sorry for my bad english)

**Comment by lcpz** [comment]
Apparently that function is post version 4.0. I'm going to revert the changes.

Also, [check if you have Gio/Glib >= 2.54](https://github.com/lcpz/lain/issues/387), otherwise don't use [`lain.widget.fs`](https://github.com/lcpz/lain/wiki/fs).

PS: Your English is good. :+1:
