### ISSUE TITLE
Clicking minimized tasklist icon does not restore associated window

### ISSUE THREAD

**Issue by xelkarin** [lcpz/awesome-copycats#240]
When clicking the tasklist icon of an already minimized window, the icon highlights white and then stops responding to additional mouse clicks. Previously the behavior was to restore the minimized window. The window can still be restored using Mod-Ctrl-N. The current behavior makes running virtualization software such as VirtualBox awkward, considering how they capture keys. Under the previous behavior I was able to minimize the virtual machine by clicking on the task list, then switch between other workspaces to work on other things, restoring the virtual machine on it's workspace by clicking on the tasklist icon when ready to work with that again.

It seems that the previous behavior was defined by the following in `rc.lua`:

```lua
if c == client.focus then
  c.minimized = true
else
  -- Without this, the following
  -- :isvisible() makes no sense
  c.minimized = false
  if not c:isvisible() and c.first_tag then
    c.first_tag:view_only()
  end
  -- This will also un-minimize
  -- the client, if needed
  client.focus = c
  c:raise()
end
```

This was recently replace with:

```lua
if c == client.focus then
    c.minimized = true
else
    c:emit_signal("request::activate", "tasklist", {raise = true})
end
```

Unless I'm mistaken, it looks like it's trying to produce the same behavior, but I'm not certain. If you had something else in mind, I could always just continue using the old code in my `rc.lua` file.

`awesome -v`
> awesome v4.2 (Human after all)
>  • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
>  • D-Bus support: ✔
>  • execinfo support: ✔
>  • xcb-randr version: 1.6
>  • LGI version: 0.9.0

`lua -v`
> Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

**Comment by lcpz** [comment]
That is taken from latest default `rc.lua`. I will just revert.
