### ISSUE TITLE
Holo theme music buttons don't work - nil value

### ISSUE THREAD

**Issue by MinallWch** [lcpz/awesome-copycats#242]
Archlinux: 4.18.9-zen1-1-zen
awesome -v output:
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
lua -v output:
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
I'm using the Holo theme, and i'm getting errors in the 4 right-up music buttons, they all have the same output when pressed:
Oops, an error happened!
/home/myuser/.config/awesome/themes/holo/theme.lua:183 attempt to call a nil value (field 'execute')
for previous buttom, and the same from the rest of the music buttons, 
188: attempt to call a nil valie (field 'execute')
194 and 199, etc
They all say that his respective field 'execute' is nil, and i don't know why, i didn't change anything from the config file except from the wallpaper.
I have all the dependencies from awesome-copycats, free-desktop and lain, with i installed from the AUR
I have mpd working, with ncmpcpp installed with i want to uninstall when the buttons work...
I don't know if the headphone or the bar in the said should do something when pressed, they don't do anything for me, but i just want to use the music buttons... 
MPD messages work
And i have mpc installed, when i run the commands that are supposed to run when i press the button, for example "mpc next", they run without problems, so i have no clue.
I use Tilda as a terminal.
Also, thank you in advantage for helping me, and also for your work.

**Comment by lcpz** [comment]
It was due to a restricted way of loading `os`. It is fixed now, thank you.
