### ISSUE TITLE
chosen_theme?

### ISSUE THREAD

**Issue by InvisibleRasta** [lcpz/awesome-copycats#249]
what does this mean ? in theme.lua, so that you just need to change chosen_theme variable in rc.lua. 
i see 
local chosen_theme = themes[5]
and
beautiful.init(string.format("%s/.config/awesome/themes/%s/theme.lua", os.getenv("HOME"), chosen_theme))

which one to change?

**Comment by lcpz** [comment]
You just have to change [this line](https://github.com/lcpz/awesome-copycats/blob/master/rc.lua.template#L88). More precisely, you have to change only the array index to the number corresponding to the theme you want. The numbers are listed [here](https://github.com/lcpz/awesome-copycats/blob/master/rc.lua.template#L76-L85) in the comments. For instance:

```lua
local chosen_theme = theme[1] -- for blackburn
```
