### ISSUE TITLE
Preserve tags after switching back from external screen

### ISSUE THREAD

**Issue by Konfekt** [lcpz/awesome-copycats#251]
For someone that uses every once in a while more than a single screen, to ensure that tag numbers are left as they were before switching back to a single default screen, how about adding (a reference to)

https://github.com/awesomeWM/awesome/issues/1382#issuecomment-430909577

to the template `rc.lua`?

**Comment by lcpz** [comment]
Since it's your use case, why don't you post a diff patch, containing the information exactly as you want?

Or you just want a simple link?

Note that someone had "side effects" with that code.
