### ISSUE TITLE
[Feature Request] Brightness Widget for powerarrow theme

### ISSUE THREAD

**Issue by GrayJack** [lcpz/awesome-copycats#256]
It's the only thing I miss about the powerarrow theme. :smiley:

**Comment by lcpz** [comment]
Why do you think it should be in the template? You can add it yourself in your clone.

**Comment by GrayJack** [comment]
I think it should be in the template cause it's a handy feature. And to have a match icon with the rest of the theme

Yeah, I can, most people using awesome long enough can, but it won't have a icon that matches the rest of the theme

**Comment by lcpz** [comment]
> Yeah, I can

I suggest you create an icon and do a PR.

**Comment by GrayJack** [comment]
I was planning to do it already when I have some free time, except for the icon part, since I don't know how

That's why I opened this issue

**Comment by lcpz** [comment]
> since I don't know how

Just find an existing icon and change the colours to match the theme.
