### ISSUE TITLE
Inconsistent borders

### ISSUE THREAD

**Issue by denzerdhard** [lcpz/awesome-copycats#261]
Lets say we on tag 5 with one tiled client and we display tag 4 with one tiled client as well so tag 5 and 4 displayed at the same time, then we have two clients but no selection border appears. If then we change focus, selection border appears. Now we focus client on tag 5 and hide tag 4 from displaying. Selection border still around client on tag 5 even if its only one client.

**Comment by denzerdhard** [comment]
Logic in https://github.com/lcpz/awesome-copycats/issues/80 seems to work better.
```
Screen.connect_signal("arrange", function (s)
    local only_one = #s.tiled_clients == 1
    for _, c in pairs(s.clients) do
        if only_one and not c.floating or c.maximized then
            c.border_width = 0
        else
            c.border_width = beautiful.border_width
        end
    end
end)
```

**Comment by lcpz** [comment]
@denzerdhard Try db3003a

**Comment by denzerdhard** [comment]
Focus border still behaves strange then selecting multiple tags or with floats.
![rec](https://user-images.githubusercontent.com/3885773/56098729-c2986100-5f1c-11e9-869a-a6efcdbe3bd1.gif)

**Comment by lcpz** [comment]
OK, I added your snippet as well.

**Comment by denzerdhard** [comment]
Thank you. In my testing border_adjust looks unneeded now. Could you leave only focus and unfocus signals?
`client.connect_signal("focus", function(c) c.border_color = beautiful.border_focus end)
 client.connect_signal("unfocus", function(c) c.border_color = beautiful.border_normal end)
`
