### ISSUE TITLE
How to setup gnome-keyring on login ?

### ISSUE THREAD

**Issue by aswinmohanme** [lcpz/awesome-copycats#266]
I have installed  manjaro awesome and setup awesome copycats(awesome theme btw :D). I want to connect to github via ssh, I have setup the ssh keys, and can connect through ssh the problem being that I have to type my passphrase everytime. To mitigate this gnome-keyring is recommended.

I have some trouble with loading gnome-keyring, how should I load this ? Any example config would help

**Comment by aswinmohanme** [comment]
I have  tried this, but it does not work 
```
 run_once({
                             "setxkbmap -option caps:swapescape",
                             "xrandr --output VGA1 --mode 1360x768 --left-of LVDS1",
                             -- system
                             "gnome-keyring-daemon --daemonize --login",
                      }) -- entries must be separated by comma
```

**Comment by lcpz** [comment]
All you need is [`ssh-agent`](https://help.github.com/en/articles/working-with-ssh-key-passphrases). Start it with X, or enable it in [`systemd`](https://wiki.archlinux.org/index.php/SSH_keys#Start_ssh-agent_with_systemd_user).

In any case, never start a keyring with Awesome.

**Comment by aswinmohanme** [comment]
Could you share your example config ?

**Comment by lcpz** [comment]
I don't need to use ssh with passwords, sorry.

I gave you links, use them.

**Comment by lcpz** [comment]
I think I've answered your question (although unrelated). Closing.
