### ISSUE TITLE
Source of Vertex icons

### ISSUE THREAD

**Issue by brianclemens** [lcpz/awesome-copycats#267]
What is the source of the icons used in the Vertex theme?  The README says fontawesome for some reason, and doesn't mention the source of the battery / network / etc png icons.

**Comment by lcpz** [comment]
> What is the source of the icons used in the Vertex theme?

The readme will redirect you to #53, where you can find a [link](http://horst3180.deviantart.com/art/Vertex-Theme-470663601). Clicking it, you'll find your [information](https://www.deviantart.com/horst3180/art/Vertex-Icons-Beta-529266721).

> for some reason

Line 22 in  Vertex's `theme.lua`. I will write it in the readme as well.

**Comment by brianclemens** [comment]
I checked #53, looked at the theme and saw different icons in the bar.  Didn't realize you used the notification icons as panel icons.

Thanks for the quick reply!
