### ISSUE TITLE
Pango dropped support for bitmap fonts

### ISSUE THREAD

**Issue by plaqdk** [lcpz/awesome-copycats#269]
Hi 

First of all thx for some awesome work here :) 

Just ran it a problem where all fonts where shown as squares in the powerarrow-dark theme
and after looking around I found that it was a change in pango which cause this problem
https://gitlab.gnome.org/GNOME/pango/issues/386

to solve the problem we have to use non bitmap fonts so if people have the .otb version of Terminus it's soled simply by removing the "xos4" from the font name

/PlaQdk

**Comment by lcpz** [comment]
I will try on low priority to find or create OTF versions of Terminus,
Tamsyn and Tamzen. Any help is appreciated.

**Comment by lcpz** [comment]
Tamsyn does not have an OTB version yet.

Tamzen has an incomplete one. See [here](https://github.com/sunaku/tamzen-font/issues/25#issuecomment-551724246).

**Comment by lcpz** [comment]
Both [Tamzen 1.11.5-1](https://github.com/sunaku/tamzen-font/releases/tag/Tamzen-1.11.5) and [Tamsyn 1.11-6](https://aur.archlinux.org/packages/tamsyn-font-otb/) have OTB support, although the rendering in Pango is still not perfect.
