### ISSUE TITLE
Feature request, modkey-tab optional cycle between instead of two-history-swapping

### ISSUE THREAD

**Issue by Torxed** [lcpz/awesome-copycats#274]
This, is usually the first thing I do when I installed Awesome: https://stackoverflow.com/a/11708588

Would be nice if this was an option in this theme thingie.
Optional so I don't get a flaming arrow up my butt for suggesting it, but since I'm installing this theme every time anyway, would be nice if there was a option (pref via ENV, like `WINDOWS_LIKE_ALT_TABBING`) to turn this feature on.

I don't know LUA well enough to pullrequest this in, so begging for implementations.

**Comment by lcpz** [comment]
The stackoverflow information might be outdated.

This is possibly trivial, but I don't have time at the moment. I suggest you to ask the [community](https://awesomewm.org/community/).

**Comment by Torxed** [comment]
It's not outdated, copy pasted it in last week and it works as a picture perfect drop in replacement for the current alt tab.

I just don't know LUA well enough to make this a bool flag at the top. Since the alt tab structure is already in itself defined in a array of commands. But sure, ill ask the community :)

**Comment by lcpz** [comment]
Which of the two codes you want? To cycle through all the windows, to cycle through every client on a tag, or both?

**Comment by Torxed** [comment]
This one:

```lua
awful.key({ modkey,           }, "Tab",
    function ()
        -- awful.client.focus.history.previous()
        awful.client.focus.byidx(-1)
        if client.focus then
            client.focus:raise()
        end
    end),

awful.key({ modkey, "Shift"   }, "Tab",
    function ()
        -- awful.client.focus.history.previous()
        awful.client.focus.byidx(1)
        if client.focus then
            client.focus:raise()
        end
    end),
```

**Comment by Torxed** [comment]
Well played, thanks a bunch!
