### ISSUE TITLE
powerarrow binclock's widget height is hard code, so it's not aways ok

### ISSUE THREAD

**Issue by energygreek** [lcpz/awesome-copycats#278]
the height is hard coded with 26, but the bar in my computer is only 20, so it can shows only 2 bits which really confusing at the beginning,         
so i suggest to get the bar height and pass it to bin clock, but i do not know how. 
```lua
-- Binary clock
local binclock = require("themes.powerarrow.binclock"){
    height = dpi(26),
    show_seconds = true,
    color_active = theme.fg_normal,
    color_inactive = theme.bg_focus
}

```

**Comment by lcpz** [comment]
[It's not, and falls back to 18](https://github.com/lcpz/awesome-copycats/blob/master/themes/powerarrow/binclock.lua#L47).

These are templates. Just set `height = 20` [here](https://github.com/lcpz/awesome-copycats/blob/master/themes/powerarrow/theme.lua#L106).
