### ISSUE TITLE
Installation process ? 

### ISSUE THREAD

**Issue by deadeert** [lcpz/awesome-copycats#284]
Hi there,

It is really unclear to me, so sorry for noob questions. 
I'm using debian 10 with awesomevm as standalone (no paired with gnome)

```
>awesome -v 
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

I followed the installation instruction, but I cannot manage to run several theme (powerarrow). 
I manage to run multicolor but it doesn't have any widget on the left top-corner. 

Where is supposed to be installed lain and freedesktop ? I tried several places :
```  
/usr/share/awesome/lib
~/.config/awesome/lib
~/.config/awesme/ 
```

my .config/awesome is as follow:
```
freedesktop  icons  lain  lib  rc.lua  themes
```

Where is supposed to be located rc.lua file ? I tried /etc/xdg/awesome/rc.lua and .config/awesome.lua (the last one seems to have priority on global xdg conf). 

When running Xephyr I don't get any error neither for powerarrow nor multicolor. For powerarrow blackscreen is displayed in the new window.

I don't really get what I missed. the installation instructions are clear, but I don't manage to make it work :/ 

Do I need to install other component ? 

Thanks you

**Comment by lcpz** [comment]
> Where is supposed to be installed lain and freedesktop ?

When you follow the steps indicated in the [Installation](https://github.com/lcpz/awesome-copycats#installation) section, you download the themes, the submodules and the `rc.lua` to `~./config/awesome`.

After that, following the [Usage](https://github.com/lcpz/awesome-copycats#usage) section, you copy `rc.lua.template` to `rc.lua` (in the same folder), modify `rc.lua` by selecting your theme as indicated, and then restart Awesome.

Some widgets will need machine-specific setups, read the [lain](https://github.com/lcpz/lain/wiki) wiki for that.

If you are new to Awesome, check the [recipes](https://awesomewm.org/recipes) page, in particular, the links of the *Setups* section.

Feel free to ask me anything else.

**Comment by deadeert** [comment]
Okay thanks for your answer.

**Comment by lcpz** [comment]
I understand you are OK, but in case, post again and I will reopen.
