### ISSUE TITLE
Holo theme error when pressing the 

### ISSUE THREAD

**Issue by gusvianadev** [lcpz/awesome-copycats#290]
Hi.

I have a little bug with the launcher widget and main menu (the one at the bottom left corner in the holo theme) .
Whenever I click it I get the error: `/home/myuser/.config/awesome/themes/holo/theme.lua:280:` attempt to index a nil value (field 'mymainmenu')`

I tried re-installing the whole awesome copycats and all the dependencies but didn't work, and I did not see any issue here related to that.

**Comment by lcpz** [comment]
Thanks, I fixed the reference to that menu, just `git pull` and you're good to go.

**Comment by gusvianadev** [comment]
Just to make sure, where do I have to git pull? Lol
I tried it in the awesome folder but obviously there's no repo init
I'm going to make the changes manually in the meantime, but just to know for the next time.
Thanks

**Comment by lcpz** [comment]
I assumed you followed the [Git installation](https://github.com/lcpz/awesome-copycats#installation).

I suggest you to do that, because you can then run `git pull` in your Awesome folder to automatically update it.

Otherwise, just download [`rc.lua.template`](https://raw.githubusercontent.com/lcpz/awesome-copycats/master/rc.lua.template) again.

**Comment by gusvianadev** [comment]
Oh, now that I think of it. I just cloned it again, and when i do `mv -bv awesome-copycats/* ~/.config/awesome/` it does move the folder, but not the git files
Is there something wrong with the command?

**Comment by gusvianadev** [comment]
I figured it out
I used instead `mv -bv awesome-copycats/* awesome-copycats/.* -t ~/.config/awesome && rm -rf awesome-copycats` and it worked just as expected... except for the part where it's supposed to remove the awesome-copycats folder, which I think it didn't do that before anyways, but now it does move the hidden git files too. You can test it if you want and add it to the readme
