### ISSUE TITLE
Hide menu when mouse leaves it not working properly

### ISSUE THREAD

**Issue by gusvianadev** [lcpz/awesome-copycats#291]
Hi.

When I uncomment that line and try it, yes, the menu hides, but even when I try to access one of the items inside it. Like, for example, if I hover on Awesome, then try to access Hotkeys or Manual or anything inside it, the menu just disappears. I think it just doesn't recognize the items inside it as part of the menu.

**Comment by lcpz** [comment]
Tell me if you like e995f1c.

**Comment by gusvianadev** [comment]
Me likey likey likey
Now it works propperly.
thx
