### ISSUE TITLE
switch to parent window after closing child window

### ISSUE THREAD

**Issue by Konfekt** [lcpz/awesome-copycats#301]
How about adding (maybe as a comment) [these few lines](https://github.com/basaran/awesomewm-backham/blob/4ce5ce4934dc694fb8014137006738ac16ce72aa/init.lua) to switch to the parent window on closing a child window, if @basaran permits?

**Comment by basaran** [comment]
of course should they like to do so. By the way I just added a condition for tag switching. You may want to pull from the master again.

**Comment by lcpz** [comment]
Sure, feel free to create a PR.

**Comment by Konfekt** [comment]
For reference: this returns the focus to the previous window, possibly on another screen, which might differ from the parent window. In practice, returning the focus to the parent window was mostly missed when the child window was shown on another screen.

**Comment by basaran** [comment]
It is the desired behavior for most work flows.  Please include the reference to the other issue to avoid double posts. https://github.com/awesomeWM/awesome/issues/1730#issuecomment-1365029982
