### ISSUE TITLE
Please figure it out thanks

### ISSUE THREAD

**Issue by nmars-cloud** [lcpz/awesome-copycats#306]
i have steamburn and i have two N/A what dependency i need install thanks

**Comment by lexxxel** [comment]
One can see that English is not your mother tongue, but your request sounds a bit rude. Your request lacks any information about your system. 
Also, you ask for support in the bug tracker.

Wild guess: you have a desktop PC but the battery widget is activated. And/Or you did not adjusted the rc.lua to your system (e.g. network adapter name)

**Comment by nmars-cloud** [comment]
hi lexxel paste a screenshot for you 
![screen2](https://github.com/lcpz/awesome-copycats/assets/72750382/9f21f56c-9799-4b6e-abc2-2ad5e135c3d5)
thanks for help

**Comment by lcpz** [comment]
You are using Steamburn, and you don't have MPD installed, or it's turned off, or it's not configured correctly.

Either set up MPD correctly, or remove the widget.

To configure the widget, [see here](https://github.com/lcpz/lain/wiki/mpd).
