### ISSUE TITLE
cannot locate gears

### ISSUE THREAD

**Issue by ellisgeek** [lcpz/awesome-copycats#33]
It looks like Awesome is failing to locate a module called gears on ubuntu 13.10.
This is on a fresh install directly from github

Here is the output when debugging with xepher:

```
env DISPLAY=:1.0 awesome -c ~/.config/awesome/rc.lua.multicolor
/home/ellisgeek/.config/awesome/rc.lua:9: module 'gears' not found:
    no field package.preload['gears']
    no file './gears.lua'
    no file '/usr/local/share/lua/5.1/gears.lua'
    no file '/usr/local/share/lua/5.1/gears/init.lua'
    no file '/usr/local/lib/lua/5.1/gears.lua'
    no file '/usr/local/lib/lua/5.1/gears/init.lua'
    no file '/usr/share/lua/5.1/gears.lua'
    no file '/usr/share/lua/5.1/gears/init.lua'
    no file '/home/ellisgeek/.config/awesome/gears.lua'
    no file '/home/ellisgeek/.config/awesome/gears/init.lua'
    no file '/etc/xdg/xdg-awesome/awesome/gears.lua'
    no file '/etc/xdg/xdg-awesome/awesome/gears/init.lua'
    no file '/etc/xdg/awesome/gears.lua'
    no file '/etc/xdg/awesome/gears/init.lua'
    no file '/usr/share/awesome/lib/gears.lua'
    no file '/usr/share/awesome/lib/gears/init.lua'
    no file './gears.so'
    no file '/usr/local/lib/lua/5.1/gears.so'
    no file '/usr/lib/x86_64-linux-gnu/lua/5.1/gears.so'
    no file '/usr/lib/lua/5.1/gears.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
/home/ellisgeek/.config/awesome/rc.lua:9: module 'gears' not found:
    no field package.preload['gears']
    no file './gears.lua'
    no file '/usr/local/share/lua/5.1/gears.lua'
    no file '/usr/local/share/lua/5.1/gears/init.lua'
    no file '/usr/local/lib/lua/5.1/gears.lua'
    no file '/usr/local/lib/lua/5.1/gears/init.lua'
    no file '/usr/share/lua/5.1/gears.lua'
    no file '/usr/share/lua/5.1/gears/init.lua'
    no file '/home/ellisgeek/.config/awesome/gears.lua'
    no file '/home/ellisgeek/.config/awesome/gears/init.lua'
    no file '/etc/xdg/xdg-awesome/awesome/gears.lua'
    no file '/etc/xdg/xdg-awesome/awesome/gears/init.lua'
    no file '/etc/xdg/awesome/gears.lua'
    no file '/etc/xdg/awesome/gears/init.lua'
    no file '/usr/share/awesome/lib/gears.lua'
    no file '/usr/share/awesome/lib/gears/init.lua'
    no file './gears.so'
    no file '/usr/local/lib/lua/5.1/gears.so'
    no file '/usr/lib/x86_64-linux-gnu/lua/5.1/gears.so'
    no file '/usr/lib/lua/5.1/gears.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by chrisco23** [comment]
I'm having almost the same problem, gears.timer not found.  I notice that awesomewm from Ubuntu apt install is "compiled against Lua 5.1.5 though:

Ubuntu 16.04.1
```
$ awesome -v
awesome v3.5.6 (For Those About To Rock)
 • Build: Sep  1 2015 11:28:53 for x86_64 by gcc version 5.2.1 (buildd@lgw01-18)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
```
```
Xepher log:
error while running function
stack traceback:
        [C]: in function 'require'
        /home/fugbert/.config/awesome/lain/helpers.lua:12: in main chunk
        [C]: in function 'require'
        /home/fugbert/.config/awesome/lain/layout/init.lua:15: in main chunk
        [C]: in function 'require'
        /home/fugbert/.config/awesome/lain/init.lua:13: in main chunk
        [C]: in function 'require'
        /home/fugbert/.config/awesome/rc.lua:16: in main chunk
error: /home/fugbert/.config/awesome/lain/helpers.lua:12: module 'gears.timer' not found:
        no field package.preload['gears.timer']
        no file './gears/timer.lua'
        no file '/usr/local/share/lua/5.1/gears/timer.lua'
        no file '/usr/local/share/lua/5.1/gears/timer/init.lua'
        no file '/usr/local/lib/lua/5.1/gears/timer.lua'
        no file '/usr/local/lib/lua/5.1/gears/timer/init.lua'
        no file '/usr/share/lua/5.1/gears/timer.lua'
        no file '/usr/share/lua/5.1/gears/timer/init.lua'
        no file '/home/fugbert/.config/awesome/gears/timer.lua'
        no file '/home/fugbert/.config/awesome/gears/timer/init.lua'
        no file '/etc/xdg/xdg-/usr/share/xsessions/awesome/awesome/gears/timer.lua'
        no file '/etc/xdg/xdg-/usr/share/xsessions/awesome/awesome/gears/timer/init.lua'
        no file '/etc/xdg/awesome/gears/timer.lua'
        no file '/etc/xdg/awesome/gears/timer/init.lua'
        no file '/usr/share/kubuntu-default-settings/kf5-settings/awesome/gears/timer.lua'
        no file '/usr/share/kubuntu-default-settings/kf5-settings/awesome/gears/timer/init.lua'
        no file '/usr/share/awesome/lib/gears/timer.lua'
        no file '/usr/share/awesome/lib/gears/timer/init.lua'
        no file './gears/timer.so'
        no file '/usr/local/lib/lua/5.1/gears/timer.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/gears/timer.so'
        no file '/usr/lib/lua/5.1/gears/timer.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './gears.so'
        no file '/usr/local/lib/lua/5.1/gears.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/gears.so'                                                                           
        no file '/usr/lib/lua/5.1/gears.so'                                                                                            
        no file '/usr/local/lib/lua/5.1/loadall.so'

```

**Comment by copycat-killer** [comment]
@chrisco23 https://github.com/copycat-killer/awesome-copycats#warning

**Comment by chrisco23** [comment]
@copycat-killer thanks for the quick response.
Any idea what is the cleanest way to remove 3.5.6 then and go for a 4+ vers?

**Comment by copycat-killer** [comment]
Uninstall 3.5.6 package as usual, then read [here](https://github.com/awesomeWM/awesome#building-and-installation).

**Comment by chrisco23** [comment]
thx again.  uninstalled per apt.  cloned, then make:

$ make
Running cmake…
-- git -> /usr/bin/git
-- asciidoc not found.
-- xmlto not found.
-- gzip -> /bin/gzip
-- ldoc not found.
-- ldoc.lua not found.
-- Not generating API documentation. Missing: ldoc.
-- convert -> /usr/bin/convert
-- Could NOT find Lua (missing:  LUA_LIBRARIES LUA_INCLUDE_DIR) 
-- Not generating manpages. Missing: asciidoc xmlto
-- Using version from git: v4.0-105-gbfb3534
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.48.1
-- Checking for module 'gdk-pixbuf-2.0'
--   Found gdk-pixbuf-2.0, version 2.32.2
-- Checking for module 'cairo'
--   Found cairo, version 1.14.6
-- Checking for module 'x11'
--   Found x11, version 1.6.3
-- Checking for module 'xcb-cursor'
--   No package 'xcb-cursor' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  awesomeConfig.cmake:153 (pkg_check_modules)
  CMakeLists.txt:17 (include)

**Comment by copycat-killer** [comment]
The errors shown are pretty eloquent, if you read them: install `xcb-cursor` and define Lua INCLUDE_DIR.

This is how I personally build:

```shell
CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONFDIR=/etc -DLUA_LIBRARY=/usr/lib64/liblua.so;/usr/lib64/libm.so -DLUA_INCLUDE_DIR=/usr/include/luajit-2.0 -DLUA_LIBRARY=/usr/lib/libluajit-5.1.so" && make
```

You need to install LuaJIT first, otherwise change the arguments accordingly.

If something still doesn't go smooth, try to solve it yourself first. If you try and fail because you have a real problem, ask Awesome IRC channel or devel.

Requesting a step-by-step help here is a no go, this repository is **not** related to building Awesome.

**Comment by HorizonShadow** [comment]
In case someone comes across this while googling:

If you want to install awesome on ubuntu, download the tarball from their website https://awesomewm.org/download/

Extract that and run make from there. Cloning their current git branch will produce an error, and generally ruin your life.

**Comment by chrisco23** [comment]
@Luke, thanks, understood.
@Josh, thanks will try that next.

**Comment by copycat-killer** [comment]
OK, if you wish, I built a DEB package of release 4.0 with LuaJIT 2.0.4: [awesome-4.0-deb.zip](https://github.com/copycat-killer/awesome-copycats/files/712413/awesome-4.0-deb.zip)

If you want an RPM, read [here](https://encrypted.google.com/search?q=convert+deb+to+rpm).

Warning
---------

I couldn't test it because I built it on Arch x64 with [AUR/dpkg 1.18.18](https://aur.archlinux.org/packages/dpkg/), therefore I take no responsibility for its proper operation. I suggest to try it only as a last option.

**Comment by chrisco23** [comment]
Thanks all and sorry the initial issue got derailed.  I really only wanted
to add a few bells and whistles to my awesome setup.

FWIW, I attempted to build awesome-4.0 per download and it was just getting
out of hand with xcb dependency hell.

I tried the deb.

Somehow I landed in i3, which I'd never even seen before.

I went completely back to the awesome 3.5.6 / Lua 5.1.5 I began with for
the moment.

**Comment by copycat-killer** [comment]
Can you tell me what went wrong with the DEB?

It would be nice if you can retry it having installed LuaJIT >= 2.0.4, Lua >= 5.3.3, and Lua-LGI >= 0.9.1.

**Comment by chrisco23** [comment]
I'm not quite sure what happened with the DEB because somehow I wound up
with i3 and no awesome.  Maybe I was trying too many things at once.
I will give it another try and report back, hopefully by Saturday as today
is hectic.

**Comment by copycat-killer** [comment]
Just try it with default config (`/usr/local/etc/xdg/awesome` or `/etc/xdg/awesome/rc.lua`), I'd like to know if the DEB is valid. Thanks.

**Comment by chrisco23** [comment]
Not quite there yet.  So far I've needed to:
1. build xcb-xutil-xrm from source.
2. apt install libreadline
3. build lua 5.3.3 from source

But so far I'm only seeing that building /usr/local/lib/liblua.a

so:

$ awesome -v
awesome: error while loading shared libraries: liblua.so.5.3: cannot open shared object file: No such file or directory
