### ISSUE TITLE
Resize is slow/buggy when using some themes.

### ISSUE THREAD

**Issue by aviau** [lcpz/awesome-copycats#45]
Hello,

Thank you for the holo theme by the way! It is awesome :)

With every theme but copland, resizing windows with the mouse (SUPER + Right click + drag) is slow/buggy. 

This has to do with the Signals function. Moving the copland signals function to other themes fixes the issue.

Maybe related to #42 ? (I have not investigated this)

**Comment by aep** [comment]
same here with the default theme (multicolor) and titlebars disabled.  @aviau  which signals did you cop over to fix it?

**Comment by copycat-killer** [comment]
@aep This thread is almost 3 years old, every information here is outdated. Does your issue happen with default `rc.lua` too?

**Comment by aep** [comment]
@copycat-killer yes, but i am now suspecting this is something with awesome itself, since it happens with other themes too.

**Comment by copycat-killer** [comment]
The themes are all identical in structure now, but since your issue happens with default configuration, it's not related to them.
